[window]
opacity = 0.90
blur = true

[font]
size = 12.0

[font.normal]
family = 'FantasqueSansM Nerd Font'
style = 'Regular'

[font.bold]
family = 'FantasqueSansM Nerd Font'
style = 'Bold'

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

# COLORSCHEMES
[colors.primary]
background = '#192835'
foreground = '#AADA4F'

[colors.normal]
black   = '#5B4375'
red     = '#426bb6'
green   = '#2286b5'
yellow  = '#5ab782'
blue    = '#93ca5b'
magenta = '#c6c842'
cyan    = '#8a5135'
white   = '#c54646'

[colors.bright]
black   = '#5B4375'
red     = '#426bb6'
green   = '#2286b5'
yellow  = '#5ab782'
blue    = '#93ca5b'
magenta = '#c6c842'
cyan    = '#8a5135'
white   = '#c54646'
