# Open certain windows as floating by default
for_window [title="Bluetooth Devices"] floating enabled
for_window [title="Volume Control"] floating enabled
for_window [title=".*Thunar.*"] floating enabled
for_window [title="Bulk Rename - Rename Multiple Files"] floating enabled
